on: 
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

name: Cargo Bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}